### ISSUE TITLE
Access to data used in paper

### ISSUE THREAD

**Issue by JiayuanDing100** [tmonjo/DeepSpaCE#1]
Hi,

Thank you for contributing to the spatial transcriptomic in this community. 

I am wondering whether we can have a way to download data (images and gene expression profiles) used in paper without Singularity dependency. Thanks!

**Comment by tmonjo** [comment]
Hi @JiayuanDing100,

Thank you for contacting us. A part of the dataset we used was deposited and is accessible from the following link. Please follow the instruction written on the website. The full dataset will be available after publishing the paper.
https://humandbs.biosciencedbc.jp/en/hum0200-v3

Thanks,

**Comment by ronzeira2** [comment]
Hi. Can you please advise how to access and download the spatial transcriptomics data used in the paper? I tired looking in https://humandbs.biosciencedbc.jp/en/hum0200-v4 , but I could not find a way to actually download the data there.

**Comment by tmonjo** [comment]
Thank you for asking about our datasets.
The spatial transcriptomics data is the Controlled-Access Data. Please follow the instruction written on the website.
https://humandbs.biosciencedbc.jp/en/data-use
If you have additional questions, would you mind directly asking to NBDC?
https://humandbs.biosciencedbc.jp/en/contact-us
